services:
  mitarashidango:
    image: ghcr.io/ultrawazer/mitarashidango:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPO_URL: https://github.com/ultrawazer/MitarashiDango.git
        BRANCH: main
    container_name: mitarashidango
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=UTC
      - SHOKO_URL=http://192.168.1.100
      - SHOKO_PORT=8111
      - SHOKO_API_KEY=
      - HW_ACCEL=auto
      - FLARESOLVERR_ENABLED=false
      - FLARESOLVERR_URL=http://flaresolverr
      - FLARESOLVERR_PORT=8191
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./appdata:/config
      - /tmp/dango-transcode:/transcode
